spring.application.name=demo

# NeonDB PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://ep-nameless-grass-aggp8z7f-pooler.c-2.eu-central-1.aws.neon.tech/labely_ai?user=neondb_owner&password=npg_bODzeh7HC4yd&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437772D5A7134743777217A25432A462D4A614E645267556B58703273357638792F42
jwt.expiration=86400000

# Cloudflare R2 Configuration
cloudflare.r2.access-key=71e017c06cb903d2968c327ab76235a2
cloudflare.r2.secret-key=d7abef2453dad1cbd9f9ca47077be1cf9e52626e0e9dd6b5ce269fb59dce015f
cloudflare.r2.bucket-name=labely-images
cloudflare.r2.account-id=8bebf1940c7d514a997005bb843dedf9
cloudflare.r2.endpoint=https://8bebf1940c7d514a997005bb843dedf9.r2.cloudflarestorage.com
cloudflare.r2.public-url=https://pub-278283f5e04b460180af4eb13ff5fbf0.r2.dev

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
